{
 "title": "Typesense Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "typesense_cluster",
    "label": "typesense_cluster",
    "query": {
     "query": "label_values(typesense_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU Active Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "typesense_metrics_system_cpu_active_percentage",
     "legendFormat": "System CPU"
    },
    {
     "expr": "typesense_metrics_system_cpu1_active_percentage",
     "legendFormat": "CPU1"
    },
    {
     "expr": "typesense_metrics_system_cpu2_active_percentage",
     "legendFormat": "CPU2"
    },
    {
     "expr": "typesense_metrics_system_cpu3_active_percentage",
     "legendFormat": "CPU3"
    },
    {
     "expr": "typesense_metrics_system_cpu4_active_percentage",
     "legendFormat": "CPU4"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "typesense_metrics_system_memory_total_bytes",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "typesense_metrics_system_memory_used_bytes",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "typesense_metrics_system_memory_total_swap_bytes",
     "legendFormat": "Total Swap"
    },
    {
     "expr": "typesense_metrics_system_memory_used_swap_bytes",
     "legendFormat": "Used Swap"
    }
   ]
  },
  {
   "title": "System Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "typesense_metrics_system_disk_total_bytes",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "typesense_metrics_system_disk_used_bytes",
     "legendFormat": "Used Disk"
    }
   ]
  },
  {
   "title": "System Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-typesense_metrics_system_network_received_bytes",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "typesense_metrics_system_network_sent_bytes",
     "legendFormat": "Sent Bytes"
    }
   ]
  },
  {
   "title": "Typesense Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "typesense_metrics_memory_active_bytes",
     "legendFormat": "Active Memory"
    },
    {
     "expr": "typesense_metrics_memory_allocated_bytes",
     "legendFormat": "Allocated Memory"
    },
    {
     "expr": "typesense_metrics_memory_fragmentation_ratio",
     "legendFormat": "Fragmentation Ratio"
    },
    {
     "expr": "typesense_metrics_memory_mapped_bytes",
     "legendFormat": "Mapped Memory"
    },
    {
     "expr": "typesense_metrics_memory_metadata_bytes",
     "legendFormat": "Metadata Memory"
    },
    {
     "expr": "typesense_metrics_memory_resident_bytes",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "typesense_metrics_memory_retained_bytes",
     "legendFormat": "Retained Memory"
    }
   ]
  }
 ]
}